import React, { useMemo } from 'react';
import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, CreditCard, Plus, ReceiptText, ShieldCheck, Target, TrendingUp, Wallet } from 'lucide-react';
import { useFinance } from '../../../context/FinanceContext';
import { useAuth } from '../../../context/AuthContext';
import { MASTER_CATEGORY_CONFIG, formatBRL } from '../../../utils/financeUtils';

const Card = ({ children, className = '' }: { children: React.ReactNode; className?: string; key?: React.Key }) => <section className={`rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm dark:border-neutral-800 dark:bg-neutral-900 ${className}`}>{children}</section>;
const Title = ({ children, action, onClick }: { children: React.ReactNode; action?: string; onClick?: () => void }) => <div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-black">{children}</h3>{action && <button onClick={onClick} className="text-[11px] font-bold text-indigo-500">{action} →</button>}</div>;

export const FinanceOverviewTab: React.FC = () => {
  const { user } = useAuth();
  const { accounts, transactions, debts, goals, emergencyFund, budget, monthIncome, monthExpenses, monthInvestments, monthDebtsPaid, netWorthSummary, monthlyClosingHistory, setSubTab, openTransactionModal } = useFinance();
  const name = String(user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'usuário').split(' ')[0];
  const income = monthIncome || budget.plannedIncome || 0;
  const balance = income - monthExpenses - monthInvestments - monthDebtsPaid;
  const usage = income > 0 ? Math.min(100, monthExpenses / income * 100) : 0;
  const activeDebts = debts.filter((item) => !['paid', 'cancelled'].includes(item.status));
  const month = budget.month || new Date().toISOString().slice(0, 7);
  const categories = useMemo(() => { const totals: Record<string, number> = {}; transactions.filter((item) => item.type === 'expense' && item.date.startsWith(month)).forEach((item) => { totals[item.masterCategory] = (totals[item.masterCategory] || 0) + item.amount; }); return Object.entries(totals).filter(([, value]) => value > 0).sort((a, b) => b[1] - a[1]); }, [transactions, month]);
  const donut = useMemo(() => { if (!categories.length || monthExpenses <= 0) return 'conic-gradient(#262626 0 100%)'; let cursor = 0; return `conic-gradient(${categories.map(([key, value]) => { const start = cursor; cursor += value / monthExpenses * 100; return `${MASTER_CATEGORY_CONFIG[key as keyof typeof MASTER_CATEGORY_CONFIG]?.color || '#6366f1'} ${start}% ${cursor}%`; }).join(',')})`; }, [categories, monthExpenses]);
  const history = useMemo(() => [...monthlyClosingHistory.slice(-11).filter((item) => item.month !== month).map((item) => ({ month: item.month, value: item.netWorth })), { month, value: netWorthSummary.netWorth }].slice(-12), [monthlyClosingHistory, month, netWorthSummary.netWorth]);
  const historyMax = Math.max(1, ...history.map((item) => Math.abs(item.value)));

  return <div className="space-y-4">
    <header className="flex flex-col gap-3 border-b border-neutral-200 pb-5 dark:border-neutral-800 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-xs text-neutral-500">Olá,</span><h1 className="text-2xl font-black">{name}</h1><p className="mt-1 text-sm text-neutral-500">Aqui está o panorama completo da sua vida financeira.</p></div><span className="text-xs capitalize text-neutral-500">{new Date().toLocaleDateString('pt-BR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</span></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
      ['Saldo total', netWorthSummary.totalAssets, `${accounts.filter((item) => item.isActive).length} contas ativas`, Wallet, 'text-emerald-500 bg-emerald-500/10'],
      ['Receitas do mês', income, `Previsto: ${formatBRL(budget.plannedIncome)}`, ArrowDownLeft, 'text-emerald-500 bg-emerald-500/10'],
      ['Despesas do mês', monthExpenses, `${usage.toFixed(1).replace('.', ',')}% da renda`, ArrowUpRight, 'text-rose-500 bg-rose-500/10'],
      ['Saldo do mês', balance, income > 0 ? `${(balance / income * 100).toFixed(1).replace('.', ',')}% da renda` : 'Sem renda registrada', TrendingUp, balance >= 0 ? 'text-indigo-500 bg-indigo-500/10' : 'text-rose-500 bg-rose-500/10'],
    ].map(([label, value, detail, Icon, color]) => { const MetricIcon = Icon as typeof Wallet; return <Card key={String(label)}><div className="flex items-center gap-3"><span className={`rounded-xl p-3 ${color}`}><MetricIcon className="h-5 w-5"/></span><div className="min-w-0"><span className="text-xs text-neutral-500">{String(label)}</span><b className={`mt-1 block truncate text-xl ${label === 'Saldo do mês' && Number(value) >= 0 ? 'text-emerald-500' : ''}`}>{formatBRL(Number(value))}</b><span className="text-[11px] text-neutral-500">{String(detail)}</span></div></div></Card>; })}</div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.8fr)_minmax(280px,1fr)]">
      <Card><div className="flex items-start justify-between"><div><h3 className="text-sm font-black">Evolução do patrimônio</h3><p className="text-xs text-neutral-500">Com base nos fechamentos mensais registrados.</p></div><b className="text-sm text-indigo-500">{formatBRL(netWorthSummary.netWorth)}</b></div><div className="mt-5 flex h-48 items-end gap-2 overflow-x-auto border-b border-neutral-200 dark:border-neutral-800">{history.map((item) => <div key={item.month} className="flex h-full min-w-12 flex-1 flex-col items-center justify-end"><div className="w-full max-w-12 rounded-t bg-gradient-to-t from-indigo-600/30 to-indigo-500" style={{ height: `${Math.max(4, Math.abs(item.value) / historyMax * 90)}%` }} title={formatBRL(item.value)}/><span className="py-2 text-[10px] capitalize text-neutral-500">{new Date(`${item.month}-01T00:00:00Z`).toLocaleDateString('pt-BR', { month: 'short', timeZone: 'UTC' }).replace('.', '')}</span></div>)}</div></Card>
      <Card><Title action="Ver detalhes" onClick={() => setSubTab('budget')}>Distribuição das despesas</Title>{categories.length ? <div className="flex items-center gap-5"><div className="relative h-36 w-36 shrink-0 rounded-full" style={{ background: donut }}><div className="absolute inset-6 grid place-items-center rounded-full bg-white text-center dark:bg-neutral-900"><span><b className="block text-sm">{formatBRL(monthExpenses)}</b><small className="text-[10px] text-neutral-500">no mês</small></span></div></div><div className="min-w-0 flex-1 space-y-2">{categories.map(([key, value]) => <div key={key} className="grid grid-cols-[auto_1fr_auto] items-center gap-2 text-[11px]"><span className="h-2 w-2 rounded-full" style={{ background: MASTER_CATEGORY_CONFIG[key as keyof typeof MASTER_CATEGORY_CONFIG]?.color }}/><span className="truncate text-neutral-500">{MASTER_CATEGORY_CONFIG[key as keyof typeof MASTER_CATEGORY_CONFIG]?.name || key}</span><b>{(value / monthExpenses * 100).toFixed(1).replace('.', ',')}%</b></div>)}</div></div> : <Empty text="Nenhuma despesa registrada neste mês."/>}</Card>
    </div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card><Title action="Ver todas" onClick={() => setSubTab('goals')}>Metas e reserva</Title><div className="space-y-4"><Goal title="Reserva de Emergência" current={emergencyFund.currentAmount} target={emergencyFund.targetAmount} icon={<ShieldCheck className="h-4 w-4"/>}/>{goals.filter((item) => item.currentAmount < item.targetAmount).slice(0, 3).map((item) => <Goal key={item.id} title={item.title} current={item.currentAmount} target={item.targetAmount} icon={<Target className="h-4 w-4"/>}/>)}</div></Card>
      <Card><Title action="Ver todas" onClick={() => setSubTab('debts')}>Dívidas</Title><div className="space-y-2">{activeDebts.slice(0, 4).map((item) => <Row key={item.id} name={item.name || item.creditor} detail={`${item.creditor} · ${item.remainingInstallments} parcelas`} value={item.currentBalance}/>)}{!activeDebts.length && <Empty text="Nenhuma dívida ativa."/>}</div></Card>
      <Card><Title action="Ver detalhes" onClick={() => setSubTab('budget')}>Orçamento do mês</Title><div className="mt-6 h-3 overflow-hidden rounded-full bg-neutral-100 dark:bg-neutral-800"><div className={`h-full rounded-full ${usage > 100 ? 'bg-rose-500' : usage >= 80 ? 'bg-amber-500' : 'bg-indigo-500'}`} style={{ width: `${usage}%` }}/></div><div className="mt-3 flex items-end justify-between"><b>{formatBRL(monthExpenses)} <span className="font-normal text-neutral-500">de {formatBRL(income)}</span></b><b>{usage.toFixed(1).replace('.', ',')}%</b></div><div className={`mt-4 rounded-xl p-3 text-xs font-bold ${balance >= 0 ? 'bg-emerald-500/10 text-emerald-600' : 'bg-rose-500/10 text-rose-500'}`}>{balance >= 0 ? `Você ainda tem ${formatBRL(balance)} disponíveis neste mês.` : `As saídas ultrapassaram a renda em ${formatBRL(Math.abs(balance))}.`}</div></Card>
      <Card><Title>Ações rápidas</Title><div className="grid grid-cols-2 gap-2"><Action label="Novo lançamento" icon={<Plus className="h-4 w-4"/>} onClick={() => openTransactionModal('expense')}/><Action label="Transferir" icon={<ArrowLeftRight className="h-4 w-4"/>} onClick={() => openTransactionModal('transfer')}/><Action label="Aportar em meta" icon={<Target className="h-4 w-4"/>} onClick={() => setSubTab('goals')}/><Action label="Simular quitação" icon={<CreditCard className="h-4 w-4"/>} onClick={() => setSubTab('debts')}/><Action label="Ajustar orçamento" icon={<Wallet className="h-4 w-4"/>} onClick={() => setSubTab('budget')}/><Action label="Ver lançamentos" icon={<ReceiptText className="h-4 w-4"/>} onClick={() => setSubTab('transactions')}/></div></Card>
    </div>
  </div>;
};

const Goal = ({ title, current, target, icon }: { title: string; current: number; target: number; icon: React.ReactNode; key?: React.Key }) => { const pct = target > 0 ? Math.min(100, current / target * 100) : 0; return <div><div className="flex items-center justify-between gap-3"><span className="flex min-w-0 items-center gap-2 text-indigo-500">{icon}<b className="truncate text-xs text-neutral-800 dark:text-neutral-200">{title}</b></span><b className="text-xs">{pct.toFixed(1).replace('.', ',')}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-neutral-100 dark:bg-neutral-800"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${pct}%` }}/></div><span className="mt-1 block text-[10px] text-neutral-500">{formatBRL(current)} / {formatBRL(target)}</span></div>; };
const Row = ({ name, detail, value, icon }: { name: string; detail?: string; value: number; icon?: React.ReactNode; key?: React.Key }) => <div className="flex items-center justify-between gap-3 rounded-xl bg-neutral-50 p-3 dark:bg-neutral-800/50"><div className="flex min-w-0 items-center gap-2 text-indigo-500">{icon}<span className="min-w-0"><b className="block truncate text-xs text-neutral-800 dark:text-neutral-200">{name}</b>{detail && <small className="block truncate text-[10px] text-neutral-500">{detail}</small>}</span></div><b className="shrink-0 text-xs">{formatBRL(value)}</b></div>;
const Action = ({ label, icon, onClick }: { label: string; icon: React.ReactNode; onClick: () => void }) => <button onClick={onClick} className="flex items-center gap-2 rounded-xl border border-neutral-200 p-2.5 text-left text-[11px] font-bold hover:bg-neutral-50 dark:border-neutral-700 dark:hover:bg-neutral-800">{icon}{label}</button>;
const Empty = ({ text }: { text: string }) => <div className="rounded-xl border border-dashed border-neutral-300 py-6 text-center text-xs text-neutral-500 dark:border-neutral-700">{text}</div>;
