import React, { useState } from 'react';
import { useFinance } from '../../../context/FinanceContext';
import { formatBRL } from '../../../utils/financeUtils';
import { FinanceBill, MasterCategory } from '../../../types/finance';
import { MASTER_CATEGORY_CONFIG } from '../../../utils/financeUtils';
import { getTodayDateString } from '../../../utils/date';
import {
  Calendar,
  AlertTriangle,
  CheckCircle2,
  Clock,
  Plus,
  CheckSquare,
  ArrowRight,
  DollarSign,
  X,
  CreditCard,
  Building2,
  ListTodo,
} from 'lucide-react';

export const FinanceBillsTab: React.FC = () => {
  const {
    bills,
    accounts,
    creditCards,
    payBill,
    generateTaskForBill,
    addBill,
    overdueBills,
    todayBills,
    upcomingBills,
  } = useFinance();

  const [isAddBillOpen, setIsAddBillOpen] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newAmount, setNewAmount] = useState('');
  const [newDueDate, setNewDueDate] = useState(getTodayDateString());
  const [newCategory, setNewCategory] = useState<MasterCategory>('custos_fixos');
  const [newAccountId, setNewAccountId] = useState(accounts[0]?.id || '');
  const [newRecurrence, setNewRecurrence] = useState<'none' | 'monthly' | 'weekly' | 'yearly'>('monthly');

  const handleCreateBill = (e: React.FormEvent) => {
    e.preventDefault();
    const amountVal = parseFloat(newAmount.replace(',', '.'));
    if (!newTitle || !amountVal) return;

    addBill({
      title: newTitle,
      amount: amountVal,
      dueDate: newDueDate,
      type: 'expense',
      status: 'pending',
      masterCategory: newCategory,
      accountId: newAccountId,
      recurrence: newRecurrence,
      isAutoGenerated: false,
    });

    setIsAddBillOpen(false);
    setNewTitle('');
    setNewAmount('');
  };

  const paidBills = bills.filter((b) => b.status === 'paid');
  const totalPendingAmount = [...overdueBills, ...todayBills, ...upcomingBills].reduce(
    (acc, b) => acc + b.amount,
    0
  );

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h3 className="text-base font-bold text-neutral-900 dark:text-neutral-100">
            Central de Contas a Pagar & Calendário
          </h3>
          <p className="text-xs text-neutral-500 dark:text-neutral-400">
            Total pendente no período:{' '}
            <strong className="text-rose-600 dark:text-rose-400">{formatBRL(totalPendingAmount)}</strong>
          </p>
        </div>

        <button
          onClick={() => setIsAddBillOpen(true)}
          className="flex items-center gap-1.5 rounded-2xl bg-neutral-900 px-4 py-2 text-xs font-bold text-white hover:bg-neutral-800 dark:bg-neutral-100 dark:text-neutral-900 transition-colors shadow-sm self-start sm:self-auto"
        >
          <Plus className="h-4 w-4" />
          <span>Adicionar Conta</span>
        </button>
      </div>

      {/* New Bill Form */}
      {isAddBillOpen && (
        <form
          onSubmit={handleCreateBill}
          className="rounded-3xl border border-neutral-200 bg-white p-5 shadow-lg dark:border-neutral-800 dark:bg-neutral-900 space-y-4 animate-in fade-in"
        >
          <div className="flex items-center justify-between border-b border-neutral-100 pb-3 dark:border-neutral-800">
            <span className="text-xs font-bold text-neutral-900 dark:text-neutral-100">
              Cadastrar Conta a Pagar
            </span>
            <button
              type="button"
              onClick={() => setIsAddBillOpen(false)}
              className="text-neutral-400 hover:text-neutral-600"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
            <div>
              <label className="text-[11px] font-bold text-neutral-600 dark:text-neutral-400 block mb-1">
                Nome da Conta
              </label>
              <input
                type="text"
                required
                value={newTitle}
                onChange={(e) => setNewTitle(e.target.value)}
                placeholder="Ex: Aluguel, Energia, Internet..."
                className="w-full rounded-xl border border-neutral-200 bg-neutral-50 p-2 text-xs text-neutral-900 dark:border-neutral-700 dark:bg-neutral-800 dark:text-neutral-100"
              />
            </div>
            <div>
              <label className="text-[11px] font-bold text-neutral-600 dark:text-neutral-400 block mb-1">
                Valor (R$)
              </label>
              <input
                type="text"
                required
                value={newAmount}
                onChange={(e) => setNewAmount(e.target.value)}
                placeholder="0,00"
                className="w-full rounded-xl border border-neutral-200 bg-neutral-50 p-2 text-xs text-neutral-900 dark:border-neutral-700 dark:bg-neutral-800 dark:text-neutral-100"
              />
            </div>
            <div>
              <label className="text-[11px] font-bold text-neutral-600 dark:text-neutral-400 block mb-1">
                Data de Vencimento
              </label>
              <input
                type="date"
                required
                value={newDueDate}
                onChange={(e) => setNewDueDate(e.target.value)}
                className="w-full rounded-xl border border-neutral-200 bg-neutral-50 p-2 text-xs text-neutral-900 dark:border-neutral-700 dark:bg-neutral-800 dark:text-neutral-100"
              />
            </div>
            <div>
              <label className="text-[11px] font-bold text-neutral-600 dark:text-neutral-400 block mb-1">
                Categoria AUVP
              </label>
              <select
                value={newCategory}
                onChange={(e) => setNewCategory(e.target.value as MasterCategory)}
                className="w-full rounded-xl border border-neutral-200 bg-neutral-50 p-2 text-xs text-neutral-900 dark:border-neutral-700 dark:bg-neutral-800 dark:text-neutral-100"
              >
                {Object.values(MASTER_CATEGORY_CONFIG).map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex justify-end gap-2">
            <button
              type="button"
              onClick={() => setIsAddBillOpen(false)}
              className="rounded-xl border border-neutral-200 px-3 py-1.5 text-xs text-neutral-600 dark:border-neutral-700 dark:text-neutral-300"
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="rounded-xl bg-indigo-600 px-4 py-1.5 text-xs font-bold text-white hover:bg-indigo-700"
            >
              Salvar Conta
            </button>
          </div>
        </form>
      )}

      {/* Groups of Bills */}

      {/* 1. Contas Atrasadas */}
      {overdueBills.length > 0 && (
        <div className="space-y-3">
          <div className="flex items-center gap-2 text-rose-600 dark:text-rose-400">
            <AlertTriangle className="h-4 w-4" />
            <h4 className="text-xs font-bold uppercase tracking-wider">
              Contas Atrasadas ({overdueBills.length})
            </h4>
          </div>

          <div className="space-y-2.5">
            {overdueBills.map((bill) => (
              <BillCard
                key={bill.id}
                bill={bill}
                onPay={() => payBill(bill.id)}
                onGenerateTask={() => generateTaskForBill(bill)}
                isOverdue
              />
            ))}
          </div>
        </div>
      )}

      {/* 2. Vencem Hoje */}
      {todayBills.length > 0 && (
        <div className="space-y-3">
          <div className="flex items-center gap-2 text-amber-600 dark:text-amber-400">
            <Clock className="h-4 w-4" />
            <h4 className="text-xs font-bold uppercase tracking-wider">
              Vencem Hoje ({todayBills.length})
            </h4>
          </div>

          <div className="space-y-2.5">
            {todayBills.map((bill) => (
              <BillCard
                key={bill.id}
                bill={bill}
                onPay={() => payBill(bill.id)}
                onGenerateTask={() => generateTaskForBill(bill)}
              />
            ))}
          </div>
        </div>
      )}

      {/* 3. Próximos 7 Dias e Futuras */}
      <div className="space-y-3">
        <div className="flex items-center gap-2 text-neutral-700 dark:text-neutral-300">
          <Calendar className="h-4 w-4 text-indigo-500" />
          <h4 className="text-xs font-bold uppercase tracking-wider">
            Próximos Vencimentos ({upcomingBills.length})
          </h4>
        </div>

        {upcomingBills.length === 0 ? (
          <div className="rounded-2xl border border-neutral-200 bg-white p-6 text-center text-xs text-neutral-400 dark:border-neutral-800 dark:bg-neutral-900">
            Nenhuma conta a vencer cadastrada para os próximos dias.
          </div>
        ) : (
          <div className="space-y-2.5">
            {upcomingBills.map((bill) => (
              <BillCard
                key={bill.id}
                bill={bill}
                onPay={() => payBill(bill.id)}
                onGenerateTask={() => generateTaskForBill(bill)}
              />
            ))}
          </div>
        )}
      </div>

      {/* 4. Contas Já Pagas no Período */}
      {paidBills.length > 0 && (
        <div className="space-y-3 pt-4 border-t border-neutral-100 dark:border-neutral-800">
          <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400">
            <CheckCircle2 className="h-4 w-4" />
            <h4 className="text-xs font-bold uppercase tracking-wider">
              Contas Pagas no Mês ({paidBills.length})
            </h4>
          </div>

          <div className="space-y-2 opacity-75">
            {paidBills.map((bill) => (
              <div
                key={bill.id}
                className="flex items-center justify-between rounded-2xl border border-neutral-200 bg-neutral-50/50 p-3.5 text-xs dark:border-neutral-800 dark:bg-neutral-800/30"
              >
                <div className="flex items-center gap-3">
                  <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400">
                    <CheckCircle2 className="h-4 w-4" />
                  </div>
                  <div>
                    <span className="font-bold text-neutral-900 dark:text-neutral-100 line-through">
                      {bill.title}
                    </span>
                    <div className="text-[11px] text-neutral-400">
                      Vencimento: {bill.dueDate} • Pago
                    </div>
                  </div>
                </div>
                <div className="font-bold text-neutral-700 dark:text-neutral-300">
                  {formatBRL(bill.amount)}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

interface BillCardProps {
  bill: FinanceBill;
  onPay: () => void;
  onGenerateTask: () => void;
  isOverdue?: boolean;
}

const BillCard: React.FC<BillCardProps> = ({ bill, onPay, onGenerateTask, isOverdue }) => {
  const catConfig = MASTER_CATEGORY_CONFIG[bill.masterCategory];

  return (
    <div
      className={`flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-2xl border p-4 transition-all ${
        isOverdue
          ? 'border-rose-300 bg-rose-50/60 dark:border-rose-900/60 dark:bg-rose-950/30'
          : 'border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900'
      }`}
    >
      <div className="flex items-center gap-3.5">
        <div
          className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl text-xs font-black shadow-sm ${
            isOverdue
              ? 'bg-rose-600 text-white'
              : 'bg-neutral-100 text-neutral-700 dark:bg-neutral-800 dark:text-neutral-200'
          }`}
        >
          {bill.dueDate.split('-')[2]}
        </div>

        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-neutral-900 dark:text-neutral-100">
              {bill.title}
            </span>
            {isOverdue && (
              <span className="rounded-full bg-rose-100 px-2 py-0.5 text-[10px] font-bold text-rose-700 dark:bg-rose-900/60 dark:text-rose-200">
                Atrasada!
              </span>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2 mt-1 text-[11px] text-neutral-500 dark:text-neutral-400">
            <span>Vencimento: {bill.dueDate}</span>
            <span>•</span>
            <span style={{ color: catConfig?.color }} className="font-semibold">
              {catConfig?.name || bill.masterCategory}
            </span>
            {bill.linkedTaskId && (
              <span className="flex items-center gap-1 text-[10px] text-indigo-600 font-bold dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950/40 px-1.5 py-0.5 rounded">
                <CheckSquare className="h-3 w-3" />
                Tarefa no Fluxo
              </span>
            )}
          </div>
        </div>
      </div>

      <div className="flex items-center justify-between sm:justify-end gap-3 pt-2 sm:pt-0 border-t sm:border-0 border-neutral-100 dark:border-neutral-800">
        <div className="text-sm font-black text-neutral-900 dark:text-neutral-100">
          {formatBRL(bill.amount)}
        </div>

        <div className="flex items-center gap-2">
          {!bill.linkedTaskId && (
            <button
              onClick={onGenerateTask}
              title="Criar lembrete nas Tarefas do Fluxo"
              className="flex items-center gap-1 rounded-xl border border-neutral-200 bg-neutral-50 px-2.5 py-1.5 text-xs font-semibold text-neutral-700 hover:bg-neutral-100 dark:border-neutral-700 dark:bg-neutral-800 dark:text-neutral-300 transition-colors"
            >
              <ListTodo className="h-3.5 w-3.5 text-indigo-600" />
              <span className="hidden md:inline">Gerar Tarefa</span>
            </button>
          )}

          <button
            onClick={onPay}
            className="flex items-center gap-1 rounded-xl bg-emerald-600 px-3 py-1.5 text-xs font-bold text-white shadow-sm hover:bg-emerald-700 active:scale-95 transition-all"
          >
            <CheckCircle2 className="h-3.5 w-3.5" />
            <span>Pagar</span>
          </button>
        </div>
      </div>
    </div>
  );
};
