export type MasterCategory =
  | 'custos_fixos'
  | 'conforto'
  | 'metas'
  | 'prazeres'
  | 'liberdade_financeira'
  | 'conhecimento';

export type TransactionType =
  | 'income'
  | 'expense'
  | 'transfer'
  | 'investment'
  | 'redemption'
  | 'debt_payment';

export type FinanceAccountType =
  | 'checking'
  | 'digital'
  | 'savings'
  | 'wallet'
  | 'brokerage'
  | 'international';

export interface FinanceAccount {
  id: string;
  name: string;
  bank: string;
  type: FinanceAccountType;
  balance: number;
  color: string;
  icon?: string;
  initialBalance?: number;
  isActive: boolean;
}

export interface CreditCard {
  id: string;
  name: string;
  bank: string;
  limit: number;
  availableLimit: number;
  closingDay: number; // Day of month
  dueDay: number; // Day of month
  color: string;
  linkedAccountId?: string;
  currentInvoice: number;
  nextInvoice: number;
}

export interface InstallmentPurchase {
  id: string;
  description: string;
  totalAmount: number;
  installmentAmount: number;
  totalInstallments: number;
  paidInstallments: number;
  startDate: string; // YYYY-MM-DD
  nextDueDate: string; // YYYY-MM-DD
  cardId: string;
  masterCategory: MasterCategory;
  subcategory?: string;
}

export interface FinanceTransaction {
  id: string;
  type: TransactionType;
  amount: number;
  date: string; // YYYY-MM-DD
  description: string;
  masterCategory: MasterCategory;
  subcategory?: string;
  accountId?: string;
  destinationAccountId?: string; // For transfers
  cardId?: string; // If paid by credit card
  projectId?: string; // Linked Fluxo project
  goalId?: string; // Linked Fluxo financial goal
  tags?: string[];
  recurrence?: 'none' | 'daily' | 'weekly' | 'monthly' | 'yearly';
  isRecurringInstance?: boolean;
  notes?: string;
  installments?: {
    current: number;
    total: number;
    purchaseId?: string;
  };
  linkedBillId?: string;
  linkedTaskId?: string;
}

export interface FinanceBill {
  id: string;
  title: string;
  amount: number;
  dueDate: string; // YYYY-MM-DD
  type: 'expense' | 'income';
  status: 'pending' | 'paid' | 'overdue';
  masterCategory: MasterCategory;
  subcategory?: string;
  accountId?: string;
  cardId?: string;
  recurrence?: 'none' | 'monthly' | 'weekly' | 'yearly';
  linkedTaskId?: string;
  isAutoGenerated?: boolean;
  notes?: string;
}

export interface FinanceDebt {
  id: string;
  creditor: string;
  type: 'loan' | 'financing' | 'credit_card' | 'overdraft' | 'personal' | 'other';
  originalAmount: number;
  currentBalance: number;
  interestRateMonthly: number; // % monthly
  totalInstallments: number;
  remainingInstallments: number;
  installmentAmount: number;
  dueDay: number;
  startDate?: string;
  endDate?: string;
  priority: 'urgent' | 'high' | 'medium' | 'low';
  notes?: string;
  status: 'active' | 'paid';
}

export interface EmergencyFund {
  targetAmount: number;
  currentAmount: number;
  monthlyContribution: number;
  targetMonths: number; // e.g. 6 months
}

export interface FinancialGoalItem {
  id: string;
  title: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string; // YYYY-MM-DD
  monthlyContribution: number;
  masterCategory: 'metas';
  linkedGlobalGoalId?: string;
  icon?: string;
  color: string;
  notes?: string;
}

export type InvestmentCategory =
  | 'renda_fixa'
  | 'acoes_br'
  | 'acoes_int'
  | 'fiis'
  | 'reits'
  | 'crypto'
  | 'etfs'
  | 'fundos'
  | 'outros';

export interface InvestmentAssetItem {
  id: string;
  tickerOrName: string;
  category: InvestmentCategory;
  quantity: number;
  averagePrice: number;
  currentPrice: number;
  totalInvested: number;
  currentValue: number;
  institution: string;
  targetAllocationPercent: number; // Target % in portfolio
  notes?: string;
}

export interface ZeroBasedBudget {
  month: string; // YYYY-MM
  plannedIncome: number;
  allocations: {
    custos_fixos: number;
    conforto: number;
    metas: number;
    prazeres: number;
    liberdade_financeira: number;
    conhecimento: number;
  };
  notes?: string;
}

export interface MonthlyClosing {
  id: string;
  month: string; // YYYY-MM
  rating: 'excellent' | 'good' | 'regular' | 'poor';
  notes: string;
  savingsRate: number;
  totalIncome: number;
  totalExpenses: number;
  totalInvested: number;
  debtsPaid: number;
  netWorth: number;
  completedAt: string;
}

export interface FinancialDiagnosisData {
  monthlyIncome: number;
  isIncomeVariable: boolean;
  fixedCosts: number;
  comfortCosts: number;
  leisureCosts: number;
  currentDebtTotal: number;
  monthlyDebtPayment: number;
  emergencyFundAmount: number;
  currentInvested: number;
  monthlyTargetInvestment: number;
  mainGoals: string;
  completedAt?: string;
}

export interface HealthScoreFactor {
  label: string;
  status: 'positive' | 'neutral' | 'negative';
  detail: string;
}

export interface FinancialHealthScore {
  score: number; // 0 - 100
  rating: 'Excelente' | 'Boa' | 'Regular' | 'Atenção';
  factors: HealthScoreFactor[];
}

export type FinanceSubTab =
  | 'overview'
  | 'emergency'
  | 'budget'
  | 'transactions'
  | 'accounts'
  | 'bills'
  | 'debts'
  | 'goals'
  | 'investments'
  | 'analytics'
  | 'assistant'
  | 'diagnosis';
